services:
  - type: web
    name: dashlytics
    env: python
    buildCommand: |
      pip install -r requirements.txt
      apt-get update
      apt-get install -y chromium
    startCommand: streamlit run app.py --server.port $PORT --server.address 0.0.0.0